const ErrorType = {
    MISSING_MANDATORY_PROPERTY: 'MISSING_MANDATORY_PROPERTY',
    MAXIMUM_LENGTH_EXCEEDED: 'MAXIMUM_LENGTH_EXCEEDED',
    INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
    END_DATE_IS_LOWER_THAN_START_DATE: 'END_DATE_IS_LOWER_THAN_START_DATE',
    INVALID_PICK_LIST_FORMAT: 'INVALID_PICK_LIST_FORMAT',
    API_KEY_MISSING: 'API_KEY_MISSING',
    API_KEY_INVALID: 'API_KEY_INVALID',
}

module.exports = ErrorType